apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ef8yfljkz-nodejs 
  janus-idp.io/tekton: ef8yfljkz-nodejs
  backstage.io/kubernetes-id: ef8yfljkz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ef8yfljkz-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml